### ISSUE TITLE
No input values being used during exploration.

### ISSUE THREAD

**Issue by MartinRogalla** [cs-au-dk/Artemis#131]
**When** I try to run Artemis on an example application that requires input in input fields to trigger a function with the options `--strategy-form-input-generation random`(default), `--path-trace-report html` and `--export-event-sequence selenium`,

I **expect** the exported files to contain input values used when firing events. 

I **observe** no such values, nor do the coverage reports indicate that input values were specified when firing the events.

-----------
Is this a bug or what options should I specify in order to obtain an execution trace consisting of inputs being used and events fired. Any help is greatly appreciated.

**Comment by BenSpencer** [comment]
Hi Martin,
There are a couple of things going on here.

First, you are right, it looks like the JSON and Selenium outputs do not attempt to show the form fillings which go along with the event sequences. I will have a look into including this information -- it seems like a bug/missing feature to me.

Do you have a concrete example of what you expect the selenium test suite to look like? I have never worked with them before myself.

In the meantime, you can see that events are being fired as follows:
* I am using a modified version of [trivial-string.html](https://github.com/cs-au-dk/Artemis/blob/master/artemis-code/tests/system/fixtures/concolic/trivial-string.html) where the alert is replaced with `alert("Error! '" + y + "'");` to show the input.
* I'm runing Artemis with `-v all` to get verbose output. [In full: `artemis -v all --coverage-report html --strategy-form-input-generation random --export-event-sequence json http://localhost:8000/trivial-string.html`]
* In the output, I can see the alert calls with different values for each event.
```
...
JAVASCRIPT ALERT:  "Error! 'wqtTTEWASQ'" 
...
JAVASCRIPT ALERT:  "Error! 'YxSuZZfHkr'" 
...
JAVASCRIPT ALERT:  "Error! 'wqtTTEWASQ'" 
...
JAVASCRIPT ALERT:  "Error! 'yNRxhztXso'"
...
```

---
(TLDR; The second part is more discussion and less directly related.)

Second, the way form filling is handled in the standard mode of Artemis is a bit tricky, and possibly explains *why* these values were left out in the first place, and why the selenium script may not perfectly match the behaviour of Artemis if we include them (obviously it doesn't match now either... just to say fixing this issue won't make the perfectly aligned).

Artemis works on sequences of event handlers which are triggered. When an event handler is triggered, the form inputs are considered parameters. So, for example, when the action sequence is "click button X" then that click event will inject some values into the form fields (according to whichever strategy is in use) and click the button. No change event is fired, unless that is the event being tested; the form field values are considered "background environment" which Artemis will change as needed to try to test its events. So it is possible in principle to generate "weird" executions like this: `1. onchange on myfield [myfield='abc']`, `2. click on mybutton [myfield='yxz']`. The form fields are not forced to be consistent with the events fired.

So if we have the single action `click on mybutton [myfield='xyz']` and generate a selenium script `1. fill myfiled='xyz'; 2. click mybutton` then we're describing something slightly different, and this selenium script would be considered a different sequence of actions by Artemis (first a fill/onchange event and then a click).

**Comment by BenSpencer** [comment]
I think the Selenium (and JSON) export should work as of bdfbea2f5d6e51379b76baad2b1250d4d2298621.

I don't have Selenium set up here to test so it would be great if you could confirm if this looks OK to you. The output generated will be like this. Is that what you would expect?

<table><thead><tr><td rowspan="1" colspan="3">iteration2</td></tr></thead><tbody><tr><td>open</td><td>http://localhost:8000/trivial-string.html</td><td></td></tr><tr><td>type</td><td>//input[@id="testinput"]</td><td>gpIxJwojEW</td></tr><tr><td>click</td><td>/html/body[1]/form[1]/button[1]</td><td></td></tr></tbody></table>

**Comment by MartinRogalla** [comment]
Hi Ben,

Thank you for the quick response and detailed explanation! I'm using the JSON output right now to replay the test-cases in Selenium, so I won't be able to give a comment about the Selenium export.

Thanks for the heads up on the differences in behavior of event firings. I will run some examples on bdfbea2 and let you know if I run into any issues.

Thanks again,

Martin

**Comment by BenSpencer** [comment]
Thanks, Let me know if you'd like the JSON formatted a different way - I just dumped out what seemed sensible.

**Comment by MartinRogalla** [comment]
I'm getting an empty export file if I try to run the `trivial-string.html` example with the following command:

```
artemis -v all --coverage-report html --strategy-form-input-generation random --export-event-sequence json http://localhost:8080/trivial-string.html
```
**Output:**
https://gist.github.com/MartinRogalla/297da6910e8e70eef79735aa9b831fba

**Comment by BenSpencer** [comment]
Hmm, that's odd. With that exact command I get 4 iterations shown in the export file (on 0ec9a9b0).

In your run, Artemis is not able to execute the first iteration (`Warning: element was invalid, skipping`), so after that, giving nothing in the export file is probably "correct". There must be something going wrong earlier.

* Does the page http://localhost:8080/trivial-string.html look/work ok in a browser or via curl?
* It's worth trying a full rebuild of artemis `make -B artemis` and trying again; sometimes the build system can get confused.

This error should only come up if Artemis finds a null element while trying to locate your target element (so it is not necessarily your target which would be null). I don't know when this can occur in "normal" operation.

**Comment by MartinRogalla** [comment]
Yes, `make -B artemis` did the trick. Thanks!
